language: node_js
sudo: false
node_js: 
  - 6
  - 8
matrix:
  allow_failures:
    - node_js: 5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
before_install:
  - apt-get update

